CREATE TABLE ADMIN.EMPLOYEE(
    ID NUMBER(19,0) NOT NULL ENABLE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    DOB DATE NOT NULL,
    MOBILE VARCHAR(10) NOT NULL UNIQUE,
    CITY VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);