CREATE TABLE ADMIN.MANAGER(
    ID NUMBER(19,0) NOT NULL ENABLE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    DOB DATE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    COMPANY VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);